services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms_management_system
    ports:
      - "8080:80"          # Apache exposed on http://localhost:8080
      - "5173:5173"        # Vite dev server for HMR
    volumes:
      - .:/var/www/html    # Mount source code into container
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: lms_management_system_db
    restart: always
    environment:
      MYSQL_DATABASE: lms_db
      MYSQL_USER: patric
      MYSQL_PASSWORD: patric
      MYSQL_ROOT_PASSWORD: 124358
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
